package com.zcc.p2p.mapper.loan;


import com.zcc.p2p.model.loan.BidInfo;

import java.util.List;
import java.util.Map;

public interface BidInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Fri Feb 22 12:32:49 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Fri Feb 22 12:32:49 CST 2019
     */
    int insert(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Fri Feb 22 12:32:49 CST 2019
     */
    int insertSelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Fri Feb 22 12:32:49 CST 2019
     */
    BidInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Fri Feb 22 12:32:49 CST 2019
     */
    int updateByPrimaryKeySelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Fri Feb 22 12:32:49 CST 2019
     */
    int updateByPrimaryKey(BidInfo record);

    Double getBidMoney();

    List<BidInfo> selectBidInfosByLoanId(Integer id);

    List<BidInfo> selectBidInfoListByPage(Map<String, Object> paramMap);

    Long selectBidInfoCountByUid(Map<String, Object> paramMap);

    //根据loanId查询对应的投资记录
    List<BidInfo> selectBidInfoListByLoanId(Integer id);
}