package com.zcc.p2p.mapper.loan;


import com.zcc.p2p.model.loan.LoanInfo;

import java.util.List;
import java.util.Map;

public interface LoanInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Fri Feb 22 12:32:49 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Fri Feb 22 12:32:49 CST 2019
     */
    int insert(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Fri Feb 22 12:32:49 CST 2019
     */
    int insertSelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Fri Feb 22 12:32:49 CST 2019
     */
    LoanInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Fri Feb 22 12:32:49 CST 2019
     */
    int updateByPrimaryKeySelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Fri Feb 22 12:32:49 CST 2019
     */
    int updateByPrimaryKey(LoanInfo record);

    /**
     * 获取历史年化收益率
     * @return historicalAverageRate
     */
    Double getHistoricalAverageRate();

    /**
     * 获取Loan列表
     * @param paramMap
     * @return
     */
    List<LoanInfo> getLoanInfoListByPage(Map<String, Object> paramMap);

    /**
     * 获取Loan列表数量
     * @param paramMap
     * @return
     */
    Long getTotalRows(Map<String, Object> paramMap);

    /**
     * 根据id查单条loanInfo
     * @param id
     * @return
     */
    LoanInfo selectLoanInfoById(Integer id);

    /**
     * 根据UID分页查询LoanInfoList
     * @param paramMap
     * @return
     */
    List<LoanInfo> selectLoanInfoListByPage(Map<String, Object> paramMap);

    //更新产品的剩余可投资金额
    int updateLeftProductMoneyById(Map<String, Object> paramMap);

    //根据产品满标状态获取LoanInfoList
    List<LoanInfo> selectLoanInfoListByProductStatus(int i);
}